---
- name: Create New Users
  hosts: all
  gather_facts: false
  tasks:
    - name: Create Users Task
      user:
        name: "{{ username }}"
        state: present
        password: "{{ password }}"
        shell: /bin/bash