Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname  = "jenkins"

    config.vm.synced_folder '.', '/vagrant', disabled: true # This is to prevent errore with synced folder with WSL

    config.vm.network "public_network"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
        v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]  # This closes seriual port - also to prevent an error with wsl
      end

    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
        ansible.extra_vars = {
            username: "mahsh",
            password: $password
            }
      end
end